FROM python:3.10

COPY ./daisie-template /app
WORKDIR /app

RUN apt-get clean && apt-get update && apt-get install -y locales locales-all

ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE:de
ENV LC_ALL de_DE.UTF-8

RUN set -ex && \
    pip install -r requirements.txt  --no-cache-dir && \
    pip install -r daisie/requirements.txt --no-cache-dir && \
    pip install gunicorn --no-cache-dir

EXPOSE 8050

CMD ["gunicorn", "-b", "0.0.0.0:8050", "main:server", "--timeout=60"]
